// js/main.js
document.addEventListener('DOMContentLoaded', () => {
    // MANUALLY UPDATE THIS VERSION WHEN YOU RELEASE A NEW LAUNCHER
    const latestVersion = "1.0.0";
    
    // This URL is personalized for your repositories.
    const baseUrl = "https://github.com/iamplayerexe/XutronCore-launcher/releases/download/v" + latestVersion;
    
    const versionSpan = document.getElementById('latest-version');
    const winLink = document.getElementById('win-link');
    const macLink = document.getElementById('mac-link');
    const linuxDebLink = document.getElementById('linux-deb-link');
    const linuxRpmLink = document.getElementById('linux-rpm-link');

    // Update version display
    if (versionSpan) {
        versionSpan.innerText = latestVersion;
    }

    // Update download links
    if (winLink) {
        winLink.href = `${baseUrl}/XutronCore-Launcher-Setup-${latestVersion}.exe`;
    }
    if (macLink) {
        macLink.href = `${baseUrl}/XutronCore-Launcher-${latestVersion}.dmg`;
    }
    
    // Check the exact filenames generated by Electron Forge in your `out/make` directory
    if (linuxDebLink) {
        linuxDebLink.href = `${baseUrl}/xutroncore-launcher_${latestVersion}_amd64.deb`;
    }
    if (linuxRpmLink) {
        linuxRpmLink.href = `${baseUrl}/xutroncore-launcher-${latestVersion}.x86_64.rpm`; // Verify this filename
    }
});